---
dependency:
  name: galaxy
  options:
    force: False
    
driver:
  name: docker

platforms:
  - name: consul-h1
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    networks:
      - name: consul

  - name: consul-h2
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    networks:
      - name: consul

  - name: consul-h3
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
    command: /sbin/init
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    environment:
      container: docker
    restart_policy: on-failure
    networks:
      - name: consul

provisioner:
  name: ansible
  
verifier:
  name: ansible
